version: '3.8'

services:
  lxmfy-pages:
    image: ghcr.io/sudo-ivan/nomadnet:master
    container_name: lxmfy-pages
    restart: unless-stopped
    volumes:
      - ./nomadnetwork:/home/nonroot/.nomadnetwork
      - ./reticulum:/home/nonroot/.reticulum
    security_opt:
      - no-new-privileges:true
      - seccomp:unconfined
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 100M
        reservations:
          cpus: '0.25'
          memory: 100M
    environment:
      - TZ=UTC
      - PYTHONUNBUFFERED=1