version: '3.8'

services:
  lxmfy-pages:
    image: ghcr.io/markqvist/nomadnet:master
    container_name: lxmfy-pages
    restart: unless-stopped
    volumes:
      - ${PWD}/nomadnetwork:/root/.nomadnetwork:Z
      - ${PWD}/reticulum:/root/.reticulum:Z
    security_opt:
      - seccomp:./seccomp.json
    cap_add:
      - CAP_WAKE_ALARM
      - CAP_DAC_OVERRIDE
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 100M
        reservations:
          cpus: '0.25'
          memory: 100M
    environment:
      - TZ=UTC
      - PYTHONUNBUFFERED=1